In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import streamlit as st
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score


In [2]:
df= pd.read_excel("dataGYM.xlsx")
df

Age  Height  weight  BMI            Class  \
0      48     4.1      86   40  Extremely obese   
1      53     4.1      91   42  Extremely obese   
2      42     4.1      95   44  Extremely obese   
3      48     4.1     100   46  Extremely obese   
4      22     4.1     104   48  Extremely obese   
...   ...     ...     ...  ...              ...   
1171   50     6.9      59   14     Under weight   
1172   49     6.9      64   15     Under weight   
1173   52     6.9      68   16     Under weight   
1174   36     6.9      73   17     Under weight   
1175   26     6.9      77   18     Under weight   

                                             Prediction  
0     Extremely obese--normal exercise+yoga+heavy di...  
1     Extremely obese--normal exercise+yoga+heavy di...  
2     Extremely obese--normal exercise+yoga+heavy di...  
3     Extremely obese--normal exercise+yoga+heavy di...  
4     Extremely obese--normal exercise+yoga+heavy di...  
...                                                 ...  
1171  Under weight--protines+carbs+normal weights ->...  
1172  Under weight--protines+carbs+normal weights ->...  
1173  Under weight--protines+carbs+normal weights ->...  
1174  Under weight--protines+carbs+normal weights ->...  
1175  Under weight--protines+carbs+normal weights ->...  

[1176 rows x 6 columns]

In [3]:
 # performing EDA
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1176 entries, 0 to 1175
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Age         1176 non-null   int64  
 1   Height      1176 non-null   float64
 2   weight      1176 non-null   int64  
 3   BMI         1176 non-null   int64  
 4   Class       1176 non-null   object 
 5   Prediction  1176 non-null   object 
dtypes: float64(1), int64(3), object(2)
memory usage: 55.2+ KB


In [4]:
df.describe()

Age       Height       weight          BMI
count  1176.000000  1176.000000  1176.000000  1176.000000
mean     39.827381     5.690017    86.190476    28.891156
std      11.912659     0.743953    27.466612    11.760665
min      20.000000     4.100000    41.000000     9.000000
25%      29.000000     5.107500    64.000000    20.000000
50%      40.000000     5.750000    86.000000    27.000000
75%      50.000000     6.225000   109.000000    36.000000
max      60.000000     6.900000   132.000000    65.000000

In [5]:
# Perform ENCODING
df['Class']=LabelEncoder().fit_transform(df['Class'])

In [6]:
df

Age  Height  weight  BMI  Class  \
0      48     4.1      86   40      1   
1      53     4.1      91   42      1   
2      42     4.1      95   44      1   
3      48     4.1     100   46      1   
4      22     4.1     104   48      1   
...   ...     ...     ...  ...    ...   
1171   50     6.9      59   14      5   
1172   49     6.9      64   15      5   
1173   52     6.9      68   16      5   
1174   36     6.9      73   17      5   
1175   26     6.9      77   18      5   

                                             Prediction  
0     Extremely obese--normal exercise+yoga+heavy di...  
1     Extremely obese--normal exercise+yoga+heavy di...  
2     Extremely obese--normal exercise+yoga+heavy di...  
3     Extremely obese--normal exercise+yoga+heavy di...  
4     Extremely obese--normal exercise+yoga+heavy di...  
...                                                 ...  
1171  Under weight--protines+carbs+normal weights ->...  
1172  Under weight--protines+carbs+normal weights ->...  
1173  Under weight--protines+carbs+normal weights ->...  
1174  Under weight--protines+carbs+normal weights ->...  
1175  Under weight--protines+carbs+normal weights ->...  

[1176 rows x 6 columns]

In [7]:
df.drop(['BMI','Class'],axis=1,inplace=True)

In [8]:
df

Age  Height  weight                                         Prediction
0      48     4.1      86  Extremely obese--normal exercise+yoga+heavy di...
1      53     4.1      91  Extremely obese--normal exercise+yoga+heavy di...
2      42     4.1      95  Extremely obese--normal exercise+yoga+heavy di...
3      48     4.1     100  Extremely obese--normal exercise+yoga+heavy di...
4      22     4.1     104  Extremely obese--normal exercise+yoga+heavy di...
...   ...     ...     ...                                                ...
1171   50     6.9      59  Under weight--protines+carbs+normal weights ->...
1172   49     6.9      64  Under weight--protines+carbs+normal weights ->...
1173   52     6.9      68  Under weight--protines+carbs+normal weights ->...
1174   36     6.9      73  Under weight--protines+carbs+normal weights ->...
1175   26     6.9      77  Under weight--protines+carbs+normal weights ->...

[1176 rows x 4 columns]

In [9]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,0:3],df.iloc[:,-1] ,test_size = 0.2, random_state=42)

In [10]:
x_train.shape

(940, 3)

In [11]:
y_train.shape

(940,)

In [12]:
le=LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [13]:
le.classes_

array(['Extremely obese--normal exercise+yoga+heavy dite control+TIPS ->Obese',
       'Healthy--fitness+protine+simple dite',
       'Obese--slow lean+protine+full dite ->Overweight',
       'Overweight--lean+cardio+protine+normal dite ->Healthy',
       'Under weight--protines+carbs+normal weights ->Healthy'],
      dtype=object)

In [14]:
le

LabelEncoder()

In [15]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [16]:
y_train.shape

(940,)

In [17]:
lr=LogisticRegression(multi_class="multinomial")
knn=KNeighborsClassifier(n_neighbors=5)
rf = RandomForestClassifier()
dt=DecisionTreeClassifier()

In [18]:
lr.fit(x_train,y_train)
knn.fit(x_train,y_train)
rf.fit(x_train,y_train)
dt.fit(x_train,y_train)



C:\Users\91829\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [19]:
y_p=lr.predict(x_test)
y_p1=knn.predict(x_test)
y_p2=rf.predict(x_test)
y_p3=dt.predict(x_test)

In [20]:
print("-------------------LOGISTICS REGRESSION-------------")
print(metrics.confusion_matrix(y_test,y_p))
print(metrics.classification_report(y_test,y_p))
accuracy_score(y_test,y_p)

-------------------LOGISTICS REGRESSION-------------
[[31  0 12  0  0]
 [ 0 32  0  7  7]
 [ 4  2 39 10  0]
 [ 0 10 12 19  0]
 [ 0  6  0  0 45]]
              precision    recall  f1-score   support

           0       0.89      0.72      0.79        43
           1       0.64      0.70      0.67        46
           2       0.62      0.71      0.66        55
           3       0.53      0.46      0.49        41
           4       0.87      0.88      0.87        51

    accuracy                           0.70       236
   macro avg       0.71      0.69      0.70       236
weighted avg       0.71      0.70      0.70       236



0.7033898305084746

In [21]:
print("-------------------KNN------------")
print(metrics.confusion_matrix(y_test,y_p1))
print(metrics.classification_report(y_test,y_p1))
accuracy_score(y_test,y_p1)

-------------------KNN------------
[[25  3 15  0  0]
 [ 0 18 14  3 11]
 [16 13 22  3  1]
 [ 6 14 11  7  3]
 [ 0  8  3  4 36]]
              precision    recall  f1-score   support

           0       0.53      0.58      0.56        43
           1       0.32      0.39      0.35        46
           2       0.34      0.40      0.37        55
           3       0.41      0.17      0.24        41
           4       0.71      0.71      0.71        51

    accuracy                           0.46       236
   macro avg       0.46      0.45      0.44       236
weighted avg       0.46      0.46      0.45       236



0.4576271186440678

In [22]:
print("-------------------RANDOM FOREST-------------")
print(metrics.confusion_matrix(y_test,y_p2))
print(metrics.classification_report(y_test,y_p2))
accuracy_score(y_test,y_p2)

-------------------RANDOM FOREST-------------
[[40  0  2  1  0]
 [ 0 41  3  1  1]
 [ 4  0 39 12  0]
 [ 0 11  5 25  0]
 [ 0  6  0  0 45]]
              precision    recall  f1-score   support

           0       0.91      0.93      0.92        43
           1       0.71      0.89      0.79        46
           2       0.80      0.71      0.75        55
           3       0.64      0.61      0.62        41
           4       0.98      0.88      0.93        51

    accuracy                           0.81       236
   macro avg       0.81      0.80      0.80       236
weighted avg       0.81      0.81      0.81       236



0.8050847457627118

In [23]:
print("-------------------DECISION TREE-------------")
print(metrics.confusion_matrix(y_test,y_p3))
print(metrics.classification_report(y_test,y_p3))
accuracy_score(y_test,y_p3)

-------------------DECISION TREE-------------
[[41  0  2  0  0]
 [ 0 40  3  1  2]
 [ 6  2 41  6  0]
 [ 0  8  3 30  0]
 [ 0  5  0  1 45]]
              precision    recall  f1-score   support

           0       0.87      0.95      0.91        43
           1       0.73      0.87      0.79        46
           2       0.84      0.75      0.79        55
           3       0.79      0.73      0.76        41
           4       0.96      0.88      0.92        51

    accuracy                           0.83       236
   macro avg       0.84      0.84      0.83       236
weighted avg       0.84      0.83      0.83       236



0.8347457627118644

In [24]:
from sklearn.ensemble import VotingClassifier
vc=VotingClassifier(estimators=[('lr',lr),('dt',dt),('rf',rf),('knn',knn)],voting='hard')
vc1=VotingClassifier(estimators=[('lr',lr),('dt',dt),('rf',rf),('knn',knn)],voting='soft')

In [25]:
vc.fit(x_train,y_train)
vc1.fit(x_train,y_train)

C:\Users\91829\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\91829\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

VotingClassifier(estimators=[('lr',
                              LogisticRegression(multi_class='multinomial')),
                             ('dt', DecisionTreeClassifier()),
                             ('rf', RandomForestClassifier()),
                             ('knn', KNeighborsClassifier())],
                 voting='soft')

In [26]:
y_pv=vc.predict(x_test)
y_pv1=vc1.predict(x_test)

In [27]:
a=vc.predict(np.array([45,4.1,86]).reshape(1,3))


In [28]:
#ENSEMBLE ACCURACY
print("VOTING CLASSIFIER HARD:-",accuracy_score(y_test,y_pv))
print("VOTING CLASSIFIER SOFT:-",accuracy_score(y_test,y_pv1))


VOTING CLASSIFIER HARD:- 0.8050847457627118
VOTING CLASSIFIER SOFT:- 0.826271186440678


In [31]:
import pickle
pickle_out=open("gym.sav","wb")
pickle.dump(vc,pickle_out)
pickle_out.close()

In [32]:
df

Age  Height  weight                                         Prediction
0      48     4.1      86  Extremely obese--normal exercise+yoga+heavy di...
1      53     4.1      91  Extremely obese--normal exercise+yoga+heavy di...
2      42     4.1      95  Extremely obese--normal exercise+yoga+heavy di...
3      48     4.1     100  Extremely obese--normal exercise+yoga+heavy di...
4      22     4.1     104  Extremely obese--normal exercise+yoga+heavy di...
...   ...     ...     ...                                                ...
1171   50     6.9      59  Under weight--protines+carbs+normal weights ->...
1172   49     6.9      64  Under weight--protines+carbs+normal weights ->...
1173   52     6.9      68  Under weight--protines+carbs+normal weights ->...
1174   36     6.9      73  Under weight--protines+carbs+normal weights ->...
1175   26     6.9      77  Under weight--protines+carbs+normal weights ->...

[1176 rows x 4 columns]